name: dropdown_plus
description: Simple and easy to use Dropdown in forms with search, keyboard navigation, offiline data source, remote data source and easy customization.
version: 1.0.0
homepage: https://github.com/Willian199
git: https://github.com/Willian199/dropdown_plus
repository: https://github.com/Willian199/dropdown_plus
issue_tracker: https://github.com/Willian199/dropdown_plus/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
